### ISSUE TITLE
Using Pathlib

### ISSUE THREAD

**Issue by gkmurthy10** [anl-polaris/polaris-dependencies#7]
https://github.com/anl-polaris/polaris-dependencies/blob/b37813807c2b5011f889f0ffb26160963c3ddca2/get-deps.py#L55

From our experience in polarisruntime, I think it's best to use Pathlib to not rely on different types of slashes, right?

**Comment by jamiecook** [comment]
Hey @gkmurthy10 - that is definitely the case in general - however here we are looking at a default path specifically for the windows platform. 

Pathlib or os.path.join are the right tools to use 99% of the time, this one is the other 1%
